### Rehaping de Dados - Reformula/Reorganiza os Dados

In [ ]:
# Criando dados
datas = pd.date_range('20190101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=datas, columns=['Var_A', 'Var_B', 'Var_C', 'Var_D'])
df

Var_A     Var_B     Var_C     Var_D
2019-01-01  0.111398  1.215392 -0.128746 -0.550928
2019-01-02  0.257291 -0.035990  0.290385 -0.462518
2019-01-03  0.757475 -0.795998  0.382636  1.175991
2019-01-04  1.669055 -1.059944  1.220916  1.261468
2019-01-05  0.425425 -0.296495 -0.596737 -1.022078
2019-01-06  0.298128  1.239022 -0.841147 -0.247939

In [ ]:
# Transposta dos Dados
dft = df.T
dft

2019-01-01  2019-01-02  2019-01-03  2019-01-04  2019-01-05  2019-01-06
Var_A    0.111398    0.257291    0.757475    1.669055    0.425425    0.298128
Var_B    1.215392   -0.035990   -0.795998   -1.059944   -0.296495    1.239022
Var_C   -0.128746    0.290385    0.382636    1.220916   -0.596737   -0.841147
Var_D   -0.550928   -0.462518    1.175991    1.261468   -1.022078   -0.247939

In [ ]:
# Dimensões dos Dados
df.shape, dft.shape

((6, 4), (4, 6))

In [ ]:
# Extraindo apenas os dados numericos, valores
df.values

array([[ 0.11139761,  1.21539176, -0.12874637, -0.55092833],
       [ 0.25729144, -0.03598994,  0.29038496, -0.46251785],
       [ 0.75747467, -0.79599817,  0.38263602,  1.1759906 ],
       [ 1.66905543, -1.0599436 ,  1.22091561,  1.26146761],
       [ 0.42542454, -0.29649529, -0.59673663, -1.02207805],
       [ 0.29812804,  1.23902199, -0.84114732, -0.24793863]])

In [ ]:
# Extraindo os Valores
dft.values

array([[ 0.11139761,  0.25729144,  0.75747467,  1.66905543,  0.42542454,
         0.29812804],
       [ 1.21539176, -0.03598994, -0.79599817, -1.0599436 , -0.29649529,
         1.23902199],
       [-0.12874637,  0.29038496,  0.38263602,  1.22091561, -0.59673663,
        -0.84114732],
       [-0.55092833, -0.46251785,  1.1759906 ,  1.26146761, -1.02207805,
        -0.24793863]])

In [ ]:
# Reshape dos Dados
v = dft.values
v.reshape((2, 12))

array([[ 0.11139761,  0.25729144,  0.75747467,  1.66905543,  0.42542454,
         0.29812804,  1.21539176, -0.03598994, -0.79599817, -1.0599436 ,
        -0.29649529,  1.23902199],
       [-0.12874637,  0.29038496,  0.38263602,  1.22091561, -0.59673663,
        -0.84114732, -0.55092833, -0.46251785,  1.1759906 ,  1.26146761,
        -1.02207805, -0.24793863]])

In [ ]:
# Função Pivot
dias = pd.date_range(start='20220101', periods=12)
dias

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# Criando lista
pessoa = ['George', 'Victor', 'Lucas']
pessoa

['George', 'Victor', 'Lucas']

In [ ]:
# Escolha Aleatorios
np.random.choice(pessoa)

'George'

In [ ]:
nome = []
gasto = []
for i in range(12):
    nome.append(np.random.choice(pessoa))
    gasto.append(np.round(np.random.rand()*150))
nome

['Lucas',
 'Lucas',
 'George',
 'Victor',
 'Lucas',
 'Victor',
 'Victor',
 'Lucas',
 'George',
 'George',
 'Victor',
 'Victor']

In [ ]:
gasto

[15.0, 13.0, 49.0, 117.0, 84.0, 4.0, 37.0, 18.0, 126.0, 112.0, 100.0, 77.0]

In [ ]:
# Criando o DataFrame
df = pd.DataFrame({'Dia': dias,
                   'Nome': nome,
                   'Gasto': gasto})
df

Dia    Nome  Gasto
0  2022-01-01   Lucas   15.0
1  2022-01-02   Lucas   13.0
2  2022-01-03  George   49.0
3  2022-01-04  Victor  117.0
4  2022-01-05   Lucas   84.0
5  2022-01-06  Victor    4.0
6  2022-01-07  Victor   37.0
7  2022-01-08   Lucas   18.0
8  2022-01-09  George  126.0
9  2022-01-10  George  112.0
10 2022-01-11  Victor  100.0
11 2022-01-12  Victor   77.0

In [ ]:
# Função Pivot
df.pivot(index='Dia', columns='Nome', values='Gasto')

Nome        George  Lucas  Victor
Dia                              
2022-01-01     NaN   15.0     NaN
2022-01-02     NaN   13.0     NaN
2022-01-03    49.0    NaN     NaN
2022-01-04     NaN    NaN   117.0
2022-01-05     NaN   84.0     NaN
2022-01-06     NaN    NaN     4.0
2022-01-07     NaN    NaN    37.0
2022-01-08     NaN   18.0     NaN
2022-01-09   126.0    NaN     NaN
2022-01-10   112.0    NaN     NaN
2022-01-11     NaN    NaN   100.0
2022-01-12     NaN    NaN    77.0

In [ ]:
# Função Pivot_table
carros = [7, 4, 3, 2, 8]
dias = pd.date_range('20190101', '20190101', periods=5)
vendedor = ['George', 'Vagner', 'Pedro', 'Vagner', 'George']
df = pd.DataFrame({'Vendas':carros, 'Data':dias, 'Vendedor':vendedor})
df

Vendas       Data Vendedor
0       7 2019-01-01   George
1       4 2019-01-01   Vagner
2       3 2019-01-01    Pedro
3       2 2019-01-01   Vagner
4       8 2019-01-01   George

In [ ]:
# Usando Pivot
'''pd.pivot(df,index='Data', columns='Vendedor', values='Vendas')
'''
# Ao Usa o Pivot dara erro, pois o index possui valores duplicados

"pd.pivot(df,index='Data', columns='Vendedor', values='Vendas')\n"

In [ ]:
# Usando Pivot_table
pd.pivot_table(df, index='Data', columns='Vendedor', values='Vendas')

Vendedor    George  Pedro  Vagner
Data                             
2019-01-01     7.5    3.0     3.0

In [ ]:
# Stack e Unstack
df = pd.read_csv('dados/nba.csv')
df.head()

FileNotFoundError: ignored

In [ ]:
# Usando o stack
stack_df = df.stack()
stack_df

In [ ]:
# Usando o Unstack, para retorna a forma padrao dos dados
udf = stack_df.unstack()
udf.head()

In [ ]:
# Usando o Melt
df = pd.DataFrame({'A': {0: 'a', 1:'b', 2:'c'},
                  'B': {0:1, 1:3, 2:5},
                  'C': {0:2, 1:4, 2:6}})
df

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B'])

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])

### Filtros e Manipulações de Dados

In [ ]:
# Criando os Dados
datas = pd.date_range('20180101', periods=600, freq='D')
df = pd.DataFrame(np.random.randn(600,5), index=datas, columns=list('ABCDE'))
df

In [ ]:
# Obtendo dados de determinada coluna
df['D'] # Dessa forma retornaram como dataseries

In [ ]:
# Obtendo dados de determinada coluna
df[['D']] # Dessa forma retornaram como DataFrame

In [ ]:
# Usando o loc
df.loc[:, ['A', 'B']]

In [ ]:
# Usando o iloc
df.iloc[1:, 0:3]

In [ ]:
# Usando o Iloc
# Primeiro linha depois coluna
df.iloc[1:, 0:3]

In [ ]:
# Usando o Iloc
# Primeiro linha depois coluna
df.iloc[[1, 5, 6], [0, 3]]

In [ ]:
# Usando o Iloc
# Primeiro linha depois coluna
df.head()

In [ ]:
# Selecionando valores mairoes que 0
df[df.A > 0].head()

### Limpeza e Estruturação dos Dados

In [ ]:
# Criando um Novo DataFrame
datas = pd.date_range('20200101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=datas, columns=['Var_A', 'Var_B', 'Var_C', 'Var_D'])
df

In [ ]:
df2 = pd.DataFrame({"A": 1,
                    "B": pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    "D": np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(['test', 'train', 'test', 'train']),
                    'F': 'Python'})
df2

In [ ]:
df.shape, df2.shape

In [ ]:
df.dtypes, df2.dtypes

In [ ]:
# Descrição dos Dados
df.describe()

In [ ]:
# Criando um novo dataframe a partir do primeiro

df1 = df.reindex(index=datas[0:4], columns=list(df.columns) + ['Var_E'])
df1

In [ ]:
# Adicionando Valores a coluna Var_E

df1.loc[datas[0]:datas[1], 'Var_E'] = 1
df1

In [ ]:
df.dtypes

In [ ]:
df1.describe()

In [ ]:
# Dados Faltantes
# Criando um novo DataFrame
datas = pd.date_range('20190101', periods=60, freq='D')
df = pd.DataFrame(np.random.randn(60, 10), index=datas, columns=list('ABCDEFGHIJ'))
df.head()

In [ ]:
# Gerando uma logica com valores NaN
df['F'] = df.F[df.F > 0]
df['G'] = df.G[df.G > 0]
df['J'] = df.J[df.J > 0]
df.head()

In [ ]:
# Visualizando as informações do df
df.info()

In [ ]:
# Visualizando Dados Nulos
df.isnull().sum()

In [ ]:
# Criando Copias para manipulação
df2 = df.copy()
df3 = df.copy()

In [ ]:
df2.head()

In [ ]:
df3.head()

In [ ]:
# O Metodo Fillna Preenche os valores faltantes
df2.F.fillna(np.mean(df2.F))
df2.head()

In [ ]:
# Limpeza
df2 = pd.DataFrame({"A": 1,
                    "B": pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    "D": np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(['test', 'train', 'test', 'train']),
                    'F': 'Python',
                    'G': [2,2,4,4],
                    'H': [np.nan,2,4,np.nan]})
df2

In [ ]:
# Verificando se Existe dados repetidos
df2.nunique()

In [ ]:
df2.nunique(axis=1, dropna=False)
df2

In [ ]:
# Removera os dados duplicados
df2.drop_duplicates(subset='G', keep='last')

In [ ]:
# Ordenação dos Dados
df.sort_values(by='A', ascending=True).head()

In [ ]:
# Ordenando da coluna b
df.sort_values(by='B', ascending=False).head()

### Importando e Exportando

In [ ]:
# Importando as Bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()

In [ ]:
# Importando os Dados
df = pd.read_csv('dados/iris.csv')
df.head()

In [ ]:
df.dtypes

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
# Stilos de Graficos
plt.style.available

In [ ]:
# Especificando qual stilo de grafico quero utiliza
plt.style.use('seaborn-paper')

In [ ]:
df = pd.read_csv('dados/train.csv')
df.head()

In [ ]:
plt.plot(df.Age, '-')